title: Chinese Learning Resources
email: jschuur@jschuur.com
description: >-
  All the best Chinese learning resources
baseurl: ""
url: "http://learnchinese.club"
twitter_username: joostschuur
author: <a href="https://twitter.com/joostschuur">Joost Schuur</a>

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

theme: jekyll-whiteglass

exclude: [ "Rakefile", README.md" ]

permalink: /:title/
paginate_path: /posts/:num/
paginate: 20

google_analytics: UA-107202787-2
last_updated: Oct 08 2017
